#
# Makefile for ACE framework
#
subdir = src/backend/security/ace
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = ace_misc.o ace_database.o ace_schema.o ace_relation.o ace_attribute.o \
       ace_proc.o

include $(top_srcdir)/src/backend/common.mk

