#
# Makefile for enhanced security features
#
subdir = src/backend/security
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = sepgsql

include $(top_srcdir)/src/backend/common.mk
