-- Binary Large Object
-- ===================

SELECT sepgsql_getcon();

SELECT lo_import('/tmp/sepgsql_test_blob', 6001);
SELECT lo_import('/tmp/sepgsql_test_blob', 6002);
SELECT lo_import('/tmp/sepgsql_test_blob', 6003);

SELECT lo_set_security(6001, 'system_u:object_r:sepgsql_blob_t:s0');
SELECT lo_set_security(6002, 'system_u:object_r:sepgsql_ro_blob_t:s0');
SELECT lo_set_security(6003, 'system_u:object_r:sepgsql_secret_blob_t:s0');
