#
# Makefile of the SE-PostgreSQL module
#
# Author: KaiGai Kohei <kaigai@ak.jp.nec.com>
#
# Copyright (c) 2007 - 2010, NEC Corporation
# Copyright (c) 2006 - 2007, KaiGai Kohei <kaigai@kaigai.gr.jp>
#
all install uninstall clean:
	$(MAKE) -C module $@
