#
# Makefile for ACE framework
#
subdir = src/backend/security/ace
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = ace_misc.o ace_database.o

include $(top_srcdir)/src/backend/common.mk

