#
# Makefile for the security subsystem
#
subdir = src/backend/security
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = access_control.o

include $(top_srcdir)/src/backend/common.mk
