#
# Makefile for common access control abstractions
#
subdir = src/backend/security/common
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = ac_misc.o ac_database.o ac_namespace.o ac_tablespace.o ac_class.o \
	ac_attribute.o ac_trigger.o

include $(top_srcdir)/src/backend/common.mk
