#
# Makefile for common access control abstractions
#
subdir = src/backend/security/common
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = ac_database.o ac_namespace.o

include $(top_srcdir)/src/backend/common.mk
