#
# Makefile for security features
#
subdir = src/backend/security
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = database.o schema.o relation.o attribute.o proc.o

include $(top_srcdir)/src/backend/common.mk
