#
# Makefile
#    Makefile for Row-level ACLs feature
#

subdir = src/backend/security/rowacl
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = rowacl.o

include $(top_srcdir)/src/backend/common.mk
