#
# Makefile
#    Makefile for utils/sepgsql : SE-PostgreSQL
#

subdir = src/backend/security/sepgsql
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = avc.o checker.o bridge.o label.o misc.o perms.o selinux.o

include $(top_srcdir)/src/backend/common.mk
