-- Basic Row-level Access Controls
-- ====================================

SELECT sepgsql_getcon();

-- cleanup previous tests
SET client_min_messages TO 'error';

DROP TABLE IF EXISTS t1;

RESET client_min_messages;

CREATE TABLE t1
(
	a	int primary key,
	b	text
);

INSERT INTO t1(security_label, a, b) VALUES
       ('system_u:object_r:sepgsql_table_t:s0',            1, 'aaa'),
       ('system_u:object_r:sepgsql_table_t:s0:c0',         2, 'bbb'),
       ('system_u:object_r:sepgsql_table_t:s0:c1',         3, 'ccc'),
       ('system_u:object_r:sepgsql_ro_table_t:s0',         4, 'ddd'),
       ('system_u:object_r:sepgsql_ro_table_t:s0:c0',      5, 'eee'),
       ('system_u:object_r:sepgsql_ro_table_t:s0:c1',      6, 'fff'),
       ('system_u:object_r:sepgsql_fixed_table_t:s0',      7, 'ggg'),
       ('system_u:object_r:sepgsql_fixed_table_t:s0:c0',   8, 'hhh'),
       ('system_u:object_r:sepgsql_fixed_table_t:s0:c1',   9, 'iii'),
       ('system_u:object_r:sepgsql_secret_table_t:s0',    10, 'aaa'),
       ('system_u:object_r:sepgsql_secret_table_t:s0:c0', 11, 'aaa'),
       ('system_u:object_r:sepgsql_secret_table_t:s0:c1', 12, 'aaa');
